Improve documentation about Nomad ACL minimum rights
containous/traefik pull request #10482
Opened 2024-02-27 12:55 UTC by Thadir

### What does this PR do?

Add missing information in documetation about what richt traefic needs in a nomad ACL setup

### Motivation

Not having this makes the documetation very incompleet and the fact its documeted in a issue is ver very dumb

### More

- [X] Added/updated documentation

### Additional Notes

2024-03-28 14:42 UTC, jspdown requested changes
Thanks for opening this PR. Just one minor suggestion:

2024-03-28 14:42 UTC, jspdown commented on docs/content/providers/nomad.md
> +The ACL rights that you should apply to this token is 'read-job' as described here in the [nomad documentation about ACL](https://developer.hashicorp.com/nomad/tutorials/access-control/access-control
```suggestion
The appropriate ACL privilege for this token is 'read-job', as outlined in the [Nomad documentation on ACL](https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-policies).
```

2024-04-03 08:22 UTC, Thadir commented
> Thanks for opening this PR. Just one minor suggestion:

Processed it its not my main lanaguage so any sugetsion is welcome.

2024-04-04 09:22 UTC, kevinpollet approved these changes
Thanks 👍

2024-04-04 09:22 UTC, rtribotte approved these changes
Thanks 👍

2024-04-05 08:00 UTC, jspdown approved these changes

2024-04-05 08:14 UTC, merged