Fix struct names in comment
containous/traefik pull request #10503
Opened 2024-03-07 08:00 UTC by hishope

### What does this PR do?

### Motivation

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

2024-03-07 08:29 UTC, rtribotte approved these changes
Thanks 👍

2024-03-07 14:03 UTC, kevinpollet requested changes

2024-03-07 14:03 UTC, kevinpollet commented on pkg/provider/docker/data.go
> +// NetworkData holds the network data to the provider.
```suggestion
// networkData holds the network data to the provider.
```

2024-03-07 14:09 UTC, kevinpollet commented
Hello @hishope,

As this pull request is a fix, could you please rebase it on branch v2.11?

2024-03-11 14:56 UTC, mmatur commented
> Hello @hishope,
> 
> As this pull request is a fix, could you please rebase it on branch v2.11?

This code has been introduced in Traefik v3.0, the PR has been rebase on v3.0 accordingly

2024-03-11 15:01 UTC, mmatur approved these changes

2024-03-14 13:52 UTC, merged