Fix HTTPRoute path type
containous/traefik pull request #10629
Opened 2024-04-18 06:33 UTC by sakaru

### What does this PR do?

Fix typo in the HTTPRoute documentation. Instead of valid path types being `Exact`, `Path`, the valid types are `Exact`, `PathPrefix`.

### Motivation

I got an error when following the documentation:
```
The HTTPRoute "http-app" is invalid: spec.rules[0].matches[0].path.type: Unsupported value: "Prefix": supported values: "Exact", "PathPrefix", "RegularExpression"
```

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

`PathPrefix` matches the docs here: https://gateway-api.sigs.k8s.io/v1alpha2/api-types/httproute/. So indeed it's the docs that were wrong, not the code.

2024-04-18 13:50 UTC, kevinpollet requested changes

2024-04-18 13:50 UTC, kevinpollet commented on docs/content/routing/providers/kubernetes-gateway.md
> +| [9]  | `type`        | Type of match against the path Value (supported types: `Exact`, `PathPrefix`, `RegularExpression`).                                                                         |
As `RegularExpression` is implementation [specific](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPPathMatch) we are not supporting it for now.

```suggestion
| [9]  | `type`        | Type of match against the path Value (supported types: `Exact`, `PathPrefix`).                                                                         |
```

2024-04-18 14:15 UTC, rtribotte approved these changes
Thanks 👍

2024-04-19 07:32 UTC, kevinpollet approved these changes
Thanks 👍

2024-04-19 08:29 UTC, nmengin approved these changes
Hey @sakaru,

Thank you for the fix!
LGTM

2024-04-19 09:06 UTC, merged