feat: update more than one LoadBalancer ip
containous/traefik pull request #6951
Opened 2020-06-23 04:05 UTC by iameli

### What does this PR do?

Traefik now updates Kubernetes Ingresses with all of the load balancer IPs from its 

Fixes #6950

I haven't yet updated any tests, but it appears to work properly.

### Motivation

We're running `external-dns` on our ingresses to keep DNS records synced up nicely. Before this change, we'd only get one of our IP records into DNS. Bad for load balancing.

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

2020-06-25 03:49 UTC, iameli commented
Remaining work on this:

* Fix tests
* I suppose if the ingress status is set correctly but the IPs are in a different order, we shouldn't update. I don't know if that's deterministic or not... probably not. Should do a set comparison rather than a list comparison.

2020-09-11 22:28 UTC, ldez commented
hello, could you take a look at https://github.com/livepeer/traefik/pull/1, thank you.

2020-09-14 15:57 UTC, iameli commented
Rebased and resolved conflicts, thanks @kevinpollet!

2020-09-14 19:41 UTC, ldez requested changes

2020-09-14 19:41 UTC, ldez commented on pkg/provider/kubernetes/ingress/client_mock_test.go
> +func (c clientMock) UpdateIngressStatus(_ *v1beta1.Ingress, _ []corev1.LoadBalancerIngress) error {
```suggestion
func (c clientMock) UpdateIngressStatus(_ *networkingv1beta1.Ingress, _ []corev1.LoadBalancerIngress) error {
```

2020-09-15 10:28 UTC, ldez approved these changes
Thanks :+1:

2020-09-15 11:00 UTC, rtribotte approved these changes
LGTM 👍

2020-09-15 11:02 UTC, jbdoumenjou approved these changes
LGTM

2020-09-15 11:48 UTC, merged