Add example for the IngressClass usage
containous/traefik pull request #7219
Opened 2020-08-27 13:30 UTC by SantoDE

### What does this PR do?

Adds an example how to use the new IngressClass with Traefik

### Motivation

Make better docs

### More

- [ ] Added/updated tests
- [x] Added/updated documentation

### Additional Notes

2020-08-27 13:41 UTC, notsureifkevin commented
LGTM :+1:

2020-08-27 15:44 UTC, ldez requested changes

2020-08-27 15:44 UTC, ldez commented on docs/content/providers/kubernetes-ingress.md
> +    ```yaml tab="IngressClass (YAML)"
```suggestion
    ```yaml tab="IngressClass"
```

2020-08-27 15:44 UTC, ldez commented on docs/content/providers/kubernetes-ingress.md
> +    ```yaml tab="Example Ingress (YAML)"
```suggestion
    ```yaml tab="Ingress"
```

2020-08-28 11:45 UTC, ldez approved these changes

2020-08-28 13:45 UTC, rtribotte approved these changes
LGTM 👌

2020-09-01 08:15 UTC, jbdoumenjou approved these changes
LGTM

2020-09-01 08:18 UTC, merged